
name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      
        options:
        - LMDA
        - LMDB
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
  
    steps:
     
      - name: code checkout
        uses: actions/checkout@v3

      - name: Run a one-line script
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          cred_id: ${{ secrets.CREDENTIALS_ID }}
        run: |
         echo " Username : ${DB_USERNAME}" >> "test.txt"
         echo "Hostname: ${DB_HOSTNAME}" >> "test.txt"
         echo "cred_id: ${cred_id}" >> "test.txt"
        
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: SecretsVariables
          path: "test.txt"
